### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#107]
Today, I got this message during setting of short-cut keys:
[https://imgur.com/538Hl7Q](https://imgur.com/538Hl7Q)
Followed by a list of details:
`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at zVirtualDesktop.frmHotKey.btnSave_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I updated to version 1.0.68 today, and also noticed again that each time I update zVD I have to manually add all my desktop wallpapers and my custom shortcut keys. I must be doing something wrong, right?

**Comment by mzomparelli** [comment]
Refer to this for losing your settings. You can get them back if you follow that. Going forward you should not lose settings.
https://github.com/mzomparelli/zVirtualDesktop/issues/105

For the error though...What hotkey did you try and setup? Does it already exist? I see where the error is happening, but I can't tell why.

**Comment by mzomparelli** [comment]
I figured out what happened here. I will fix tonight.

**Comment by mzomparelli** [comment]
So, I think what you did here was edit a hotkey and chose a new hotkey. I mishandled that. I'm going to publish another 1.0.68 soon to correct this issue.

**Comment by oywino** [comment]
Yes, that's correct. I tried to edit a hotkey (mouse), but it failed. So I found I first had to delete the key and then recreate it.

**Comment by mzomparelli** [comment]
I published a new 1.0.68 for you to test out and try and reproduce what you did to check if the issue is resolved.

https://zomp.co/files.aspx?id=zvd

**Comment by mzomparelli** [comment]
Thanks for posting the stack trace (that's the piece that I left after editing you issue text). That allows me to see exactly where the error occurred. Some users only post screen shots of the error box which is mostly useless.
