### ISSUE TITLE
Slide show on all desktops from directory

### ISSUE THREAD

**Issue by linuxaos** [mzomparelli/zVirtualDesktop#168]
Simple, instead of specifying a background, specify a directory and create a slide show which lasts 1,2,5,10 minutes, etc.

**Comment by mzomparelli** [comment]
That's a nice idea, thanks!

**Comment by linuxaos** [comment]
I registered 3 computers. Very nice software. Thank you!

-G

**Comment by mzomparelli** [comment]
I'm working on this and it will be in the next release.

**Comment by mzomparelli** [comment]
Send me an email and ask me for a test version with this feature. I want to work out all of the kinks before I publish.

![image](https://user-images.githubusercontent.com/10564234/38001166-031f9928-31f1-11e8-8610-37bd65530798.png)

**Comment by mzomparelli** [comment]
I just published 1.0.79.2 with this feature.

**Comment by linuxaos** [comment]
That was quick!

**Comment by linuxaos** [comment]
Michael,

Downloaded 1.0.79.2 and I am getting errors.
For instance,

I click on desktop ->Edit Slideshow->Add slideshow image
I browse image and select picture
Select stretched, duration 60 seconds
Then, Save ... oops, we crash. Select continue and copy+paste
Normal image (no slideshow) works ok
-------------------------------------------------------------------------------------------
See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance 
of an object.
    at zVirtualDesktop.Slideshow.btnSave_Click(Object sender, EventArgs e)
    at System.Windows.Forms.Control.OnClick(EventArgs e)
    at System.Windows.Forms.Button.OnClick(EventArgs e)
    at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons 
button, Int32 clicks)
    at System.Windows.Forms.Control.WndProc(Message& m)
    at System.Windows.Forms.ButtonBase.WndProc(Message& m)
    at System.Windows.Forms.Button.WndProc(Message& m)
    at 
System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 
msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
     Assembly Version: 4.0.0.0
     Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
     CodeBase: 
file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
zVirtualDesktop
     Assembly Version: 1.0.79.2
     Win32 Version: 1.0.79.2
     CodeBase: file:///G:/opt/zVirtualDesktop/zVirtualDesktop.exe
----------------------------------------
System.Core
     Assembly Version: 4.0.0.0
     Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
     CodeBase: 
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
     Assembly Version: 4.0.0.0
     Win32 Version: 4.7.2556.0 built by: NET471REL1
     CodeBase: 
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
     Assembly Version: 4.0.0.0
     Win32 Version: 4.7.2556.0 built by: NET471REL1
     CodeBase: 
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
     Assembly Version: 4.0.0.0
     Win32 Version: 4.7.2556.0 built by: NET471REL1
     CodeBase: 
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
PresentationCore
     Assembly Version: 4.0.0.0
     Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
     CodeBase: 
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
WindowsBase
     Assembly Version: 4.0.0.0
     Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
     CodeBase: 
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Configuration
     Assembly Version: 4.0.0.0
     Win32 Version: 4.7.2556.0 built by: NET471REL1
     CodeBase: 
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
     Assembly Version: 4.0.0.0
     Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
     CodeBase: 
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ServiceModel
     Assembly Version: 4.0.0.0
     Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
     CodeBase: 
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
SMDiagnostics
     Assembly Version: 4.0.0.0
     Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
     CodeBase: 
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.Runtime.Serialization
     Assembly Version: 4.0.0.0
     Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
     CodeBase: 
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.ServiceModel.Internals
     Assembly Version: 4.0.0.0
     Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
     CodeBase: 
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
Microsoft.VisualStudio.Diagnostics.ServiceModelSink
     Assembly Version: 4.0.0.0
     Win32 Version: 12.0.21005.1
     CodeBase: 
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualStudio.Diagnostics.ServiceModelSink/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Diagnostics.ServiceModelSink.dll
----------------------------------------
System.IdentityModel
     Assembly Version: 4.0.0.0
     Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
     CodeBase: 
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll
----------------------------------------
System.Web
     Assembly Version: 4.0.0.0
     Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
     CodeBase: 
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Management
     Assembly Version: 4.0.0.0
     Win32 Version: 4.7.2556.0 built by: NET471REL1
     CodeBase: 
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Net.Http
     Assembly Version: 4.0.0.0
     Win32 Version: 4.7.2556.0 built by: NET471REL1
     CodeBase: 
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Accessibility
     Assembly Version: 4.0.0.0
     Win32 Version: 4.7.2556.0 built by: NET471REL1
     CodeBase: 
file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
     <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by mzomparelli** [comment]
I just published another that should fix that crash. Keep in mind this is still being tested. Please continue to report issues.

I have plans to enhance this more by allowing multi select. Another enhancement would be to use a directory like you have originally requested.

**Comment by mzomparelli** [comment]
A bug that I've encountered already is that you need to restart zVD after editing a slideshow or it plays the slides incorrectly.

**Comment by linuxaos** [comment]
No worries, I know we are testing here.

George

**Comment by mzomparelli** [comment]
I published an update to fix some bugs with the slideshow feature. The up/down buttons for reordering are still non-functional. I should get to that this weekend.

**Comment by mzomparelli** [comment]
I personally don't use the slideshow feature so testing it is less of a priority to me. Feel free to encourage me to make it better :)

**Comment by linuxaos** [comment]
Mike,

I have a quick/stupid question:

What do the up/down arrows in the slideshow pane (to the left of the 
picture) do?

Thanks,

George

**Comment by mzomparelli** [comment]
The intention was to rearrange the images. I'm not sure I handled that though so they might actually do nothing. The slideshow is an experimental feature.
