### ISSUE TITLE
Microsoft .NET Framwork error

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#194]
Hi, I'm moving everything to a new computer which has a clean installed Windows 10 Pro 1803 64-bit. Running zVD seems to be ok, but when I click on the taskbar icon, I get a window that says "Microsoft .NET Framwork error"
https://imgur.com/JpLailj
I then have to click three times on "Continue" before it actually continues.
I do not have this problem on my other PC - which was gradually updated to Win10 Pro 1803.

**Comment by mzomparelli** [comment]
Click the details button and copy the stack trace here.

**Comment by oywino** [comment]
************** Exception Text **************
System.ArgumentException: File format is not valid.
   at System.Windows.Forms.RichTextBox.StreamIn(Stream data, Int32 flags)
   at System.Windows.Forms.RichTextBox.StreamIn(String str, Int32 flags)
   at System.Windows.Forms.RichTextBox.set_Rtf(String value)
   at System.Windows.Forms.RichTextBox.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBoxBase.WndProc(Message& m)
   at System.Windows.Forms.RichTextBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by mzomparelli** [comment]
I had a reason for using RichTextBox and I don't know why it's causing this error. I changed to an ordinary TextBox and this should resolve your issue.

**Comment by oywino** [comment]
I have no idea what "box" you are referring to, but now it's ok again :)

**Comment by mzomparelli** [comment]
The boxes on DesktopView where you type the name of the desktop. I'm glad it's working ok now.
