### ISSUE TITLE
zVirtualDesktop has stopped working

### ISSUE THREAD

**Issue by darthmongo** [mzomparelli/zVirtualDesktop#265]
I keep getting this error when launching the app, even after a restart:  "zVirtualDesktop has stopped working."  

Here is information from the Event Viewer:

Faulting application name: zVirtualDesktop.exe, version: 1.0.95.4, time stamp: 0x5f0cc93f
Faulting module name: KERNELBASE.dll, version: 10.0.19041.329, time stamp: 0xa2224bb6
Exception code: 0xe0434352
Fault offset: 0x00129862
Faulting process id: 0x3184
Faulting application start time: 0x01d6597c4588e95b
Faulting application path: C:\zVirtualDesktop\zVirtualDesktop.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 9cc964b3-94a2-4229-8916-6b0a4c42de24
Faulting package full name: 
Faulting package-relative application ID: 

[PC_Info.zip](https://github.com/mzomparelli/zVirtualDesktop/files/4915982/PC_Info.zip)

**Comment by darthmongo** [comment]
I found this in the Event Viewer as well:

Application: zVirtualDesktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Security.Cryptography.CryptographicException
   at System.Security.Cryptography.RijndaelManagedTransform.DecryptData(Byte[], Int32, Int32, Byte[] ByRef, Int32, System.Security.Cryptography.PaddingMode, Boolean)
   at System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[], Int32, Int32)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean)
   at System.IO.Stream.Close()
   at CodeCollection.ConcatInitializer(System.Object, CodeCollection)
   at WindowsDesktop.Producers.VisitorInfoProducer.FillProduct(Byte[])
   at TokenCollection.ConcatInitializer(System.Object, Byte[], TokenCollection)
   at WindowsDesktop.Producers.VisitorInfoProducer.CalculateProduct(Byte[])
   at ComparatorCollection.ConcatInitializer(System.Object, Byte[], ComparatorCollection)
   at WindowsDesktop.Producers.VisitorInfoProducer.PostProduct(System.String)

Exception Info: System.Reflection.TargetInvocationException
   at zVirtualDesktop.Objects.SerializerPrototypeObject+TokenResolver.ValidateSystem(Boolean ByRef)
   at PoolParams.ConcatInitializer(System.Object, Boolean ByRef, PoolParams)
   at zVirtualDesktop.Objects.SerializerPrototypeObject+TokenResolver.DestroySystem()
   at RecordParameter.ConcatInitializer(System.Object, RecordParameter)
   at zVirtualDesktop.Objects.SerializerPrototypeObject.CloneSystem[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Int32, System.Object[], System.Object, Int32 ByRef)
   at zVirtualDesktop.Objects.SerializerPrototypeObject.NewSystem(Int32, System.Object[], System.Object)
   at BaseListener.ConcatInitializer(Int32, System.Object[], System.Object, BaseListener)
   at zVirtualDesktop.Managers.InterpreterAuthenticationManager.ExcludePrototype(System.String)

Exception Info: System.Reflection.TargetInvocationException
   at zVirtualDesktop.Objects.SerializerPrototypeObject+TokenResolver.ValidateSystem(Boolean ByRef)
   at PoolParams.ConcatInitializer(System.Object, Boolean ByRef, PoolParams)
   at zVirtualDesktop.Objects.SerializerPrototypeObject+TokenResolver.DestroySystem()
   at RecordParameter.ConcatInitializer(System.Object, RecordParameter)
   at zVirtualDesktop.Objects.SerializerPrototypeObject.CloneSystem[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Int32, System.Object[], System.Object, Int32 ByRef)
   at zVirtualDesktop.Objects.SerializerPrototypeObject.NewSystem(Int32, System.Object[], System.Object)
   at BaseListener.ConcatInitializer(Int32, System.Object[], System.Object, BaseListener)
   at zVirtualDesktop.Settings.GetEmailAddress()

Exception Info: System.Reflection.TargetInvocationException
   at zVirtualDesktop.Objects.SerializerPrototypeObject+TokenResolver.ValidateSystem(Boolean ByRef)
   at PoolParams.ConcatInitializer(System.Object, Boolean ByRef, PoolParams)
   at zVirtualDesktop.Objects.SerializerPrototypeObject+TokenResolver.DestroySystem()
   at RecordParameter.ConcatInitializer(System.Object, RecordParameter)
   at zVirtualDesktop.Objects.SerializerPrototypeObject.CloneSystem[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Int32, System.Object[], System.Object, Int32 ByRef)
   at zVirtualDesktop.Objects.SerializerPrototypeObject.NewSystem(Int32, System.Object[], System.Object)
   at BaseListener.ConcatInitializer(Int32, System.Object[], System.Object, BaseListener)
   at zVirtualDesktop.Models.DecoratorWrapper.PrintObject()

Exception Info: System.Reflection.TargetInvocationException
   at zVirtualDesktop.Objects.SerializerPrototypeObject+TokenResolver.ValidateSystem(Boolean ByRef)
   at PoolParams.ConcatInitializer(System.Object, Boolean ByRef, PoolParams)
   at zVirtualDesktop.Objects.SerializerPrototypeObject+TokenResolver.DestroySystem()
   at RecordParameter.ConcatInitializer(System.Object, RecordParameter)
   at zVirtualDesktop.Objects.SerializerPrototypeObject.CloneSystem[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Int32, System.Object[], System.Object, Int32 ByRef)
   at zVirtualDesktop.Objects.SerializerPrototypeObject.NewSystem(Int32, System.Object[], System.Object)
   at BaseListener.ConcatInitializer(Int32, System.Object[], System.Object, BaseListener)
   at zVirtualDesktop.Models.ServiceWatcherModel.CreateResolver()
   at IdentifierParameter.ConcatInitializer(IdentifierParameter)
   at zVirtualDesktop.Models.ServiceWatcherModel+<>c.<StartActivationThread>b__28_0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by mzomparelli** [comment]
What were you doing before the app crashed? I only use crypto for securing license info.

**Comment by mzomparelli** [comment]
I see that you said it happens upon starting the app. Has it run successfully at all on your machine? Can you try deleting the settings file (%appdata%\zVirtualDesktop\zVirtualDesktop_Settings.bin) and then executing the app again?

**Comment by darthmongo** [comment]
Yes, it does happen when starting the app, even from a fresh reboot of the
machine.  It has worked in the past on this machine.  Just suddenly started
happening today.  The only change I've made to my system was over the
weekend, I swapped in a new CPU cooler.  No software was changed.

I deleted the settings file and relaunched the app.  Same error.

I'm seeing a number of "edgeupdate" entries in the event log just before
this issue started.

--Aaron

**Comment by mzomparelli** [comment]
Can you check if there is any relevant info in the zVD log file?

%appdata%\zVirtualDesktop\zVirtualDesktop_Log.csv

**Comment by darthmongo** [comment]
Nothing that I can see, but I'm attaching the file here.

**Comment by mzomparelli** [comment]
It doesn't look like you attached the log here, but I believe you that it doesn't show anything relevant. 

It looks like you are running Windows 10 2004. Can you try executing the zVD build for this version of Windows? I'm wondering if it's crashing while trying to extract the downloader. This downloader, or rather the fact that zVD has it embedded in its exe is something that Virus Detectors are currently giving me a hard time about. I'm probably going to have to remove the auto-update feature or make a zVD installer to get around the false positives that occur sometimes.

The 2004 version is the same as 1809, 1903, and 1909 so this might not be your issue, but it's worth a try.

https://zvirtualdesktop.com/files.aspx?id=zvd

**Comment by darthmongo** [comment]
So, I ended up rebuilding my system, and the executable works now, although I'm sticking on the 1909 version for now.  However, I now see Defender quarantining it.  I restored it and whitelisted the app.  I don't recall Defender getting triggered on it before.

**Comment by mzomparelli** [comment]
Yeah, that's new. I'm pretty sure I know why Defender is triggered and have mentioned it in issue 266. - https://github.com/mzomparelli/zVirtualDesktop/issues/266
