### ISSUE TITLE
zVD crashes almost daily now

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#313]
Sorry to have to report that over the past year or so, zVD crashes has slowly but steadily increased, until now - it crashes almost daily. I have it running on a Win10 22H2 - fully updated DELL i7 PC that runs 24/7
There's no error messages on-screen. I'm not sure if there's a log somewhere that I could drop onto pastebin for you?
This is now becoming annoying.

**Comment by mzomparelli** [comment]
send me the log file located at %appdata%\zVirtualDesktop\zVirtualDesktop_Log.csv

You can send the file to support@zVirtualDesktop.com

The log file may not contain information on the crash so we may have to tweak the program to help us get more info.

**Comment by mzomparelli** [comment]
Also you might be able to find information on the crash in the Windows Event Viewer. I obfuscate the code so the names you see in stack traces won't be accurate, but it may be enough for me to see what is going on. Look in your Event Viewer for the log entries where the app crashed. There should be two events for every crash.

**Comment by oywino** [comment]
Hi, My log file is 226Mb in size. Too much for any email system so I had to ZIP it down.
The event viewer has lots of entries like this:
```
Faulting application name: zVirtualDesktop.exe, version: 1.0.98.15, time stamp: 0x6339d961
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2364, time stamp: 0x1e5c8604
Exception code: 0xe0434352
Fault offset: 0x0012e292
Faulting process id: 0x1504
Faulting application start time: 0x01d91002c0af8f63
Faulting application path: C:\Users\eBruker\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\zVirtualDesktop.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 8dfd31d2-e628-4688-98b6-8bd43059f5bf
Faulting package full name: 
Faulting package-relative application ID: 
```
and this:

```
Application: zVirtualDesktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Collections.Hashtable.Insert(System.Object, System.Object, Boolean)
   at System.Collections.Hashtable.set_Item(System.Object, System.Object)
   at System.Windows.Forms.Application+ThreadContext..ctor()
   at System.Windows.Forms.Application+ThreadContext.FromCurrent()
   at System.Windows.Forms.Application.DoEvents()
   at FactoryIterator.MoveFactory(FactoryIterator)
   at zVirtualDesktop.Pools.ServerInitializer.SelectComposer()
   at InitializerGetter.MoveFactory(InitializerGetter)
   at zVirtualDesktop.Pools.ServerInitializer+<>c.<StartKeyboardHook>b__75_0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by mzomparelli** [comment]
How frequently does the program experience crashes? And once it loads up, about how much time elapses before a crash occurs?

**Comment by oywino** [comment]
It's difficult to say cause I don't really notice until it happens. November was really bad. Almost daily. But last week has been much better. I don't think zVD itself is causing this. There must something else influencing which perhaps only may be present on my PC

Meybe not relevant, but I noticed that my wireless Logitech mouse also began to behave erratically during November; When I drag windows around on the screen (or do drag'n'drops) it suddenly loose focus for a fraction of a second before resuming again.This causes files and/or folders to be "dropped off" during "flight" and end up in random places.  selecting screen snippets became impossible. Then I changed to a wired mouse and everything was OK. But my wired mouse doesn't have the extra set of special keys I use for zVD flipping.

**Comment by mzomparelli** [comment]
It seems that the issue you are experiencing with your mouse is a common one that often occurs as the device ages. It appears that the left click button is not staying pressed when held, and instead behaves as if it is being clicked repeatedly, even when this is not the case. This issue may be due to wear and tear on the mouse's internal components and I have seen it happen with several of my own Logitech mice. Unfortunately, the only remedy is to buy a new mouse. It is possible to correct the issue sometimes, but usually just easier to buy a new mouse. This issue is not specific to a model of mouse but rather just seems to happen as natural wear and tear. It may happen sooner or it may never happen at all. Could this be your mouse issue?

I don't think this has anything to do with zVD crashing though.

**Comment by mzomparelli** [comment]
If the mouse is wireless it may also be interference or the mouse is too far from the receiver and a good connection is not possible.

Regarding the zVD crashing, we will need to work together to identify the cause of the issue through custom builds and further investigation.

**Comment by mzomparelli** [comment]
Your zVD log file is very large. Can I ask you to delete the zVD log file so that it starts a brand new one? Then make the program crash and then send me the new log file.

**Comment by oywino** [comment]
Thank you very much for the "mouse-info". It sound very plausible. I will replace it. Right now, I use a wired mouse. Strangely, zVD hasn't crashed on me after this months tuesday update of Windows. But I will delete the file, and let you know (send a copy) as soon as it crashes again. Thank you ever so much for your excellent support! 🙂👍🎄

**Comment by mzomparelli** [comment]
That is great to hear that you have not had zVD crash in a while. Please come back here if it happens again.

Also, I hope your mouse issue gets resolved. I know how annoying that particular issue can be.

**Comment by oywino** [comment]
I bought a new wireless mouse on monday, and it's been stable since.

**Comment by oywino** [comment]
After being stable for a good period, zVD again crashed on me twice in the past days. I sent you my log in PM

**Comment by oywino** [comment]
The past two weeks, zVD crashes many times daily.  It's so sad cause I've made myself addicted to zVD....  😥
