### ISSUE TITLE
zVD Crash

### ISSUE THREAD

**Issue by mzomparelli** [mzomparelli/zVirtualDesktop#91]
Putting this here in case any others sees this same crash stack trace. I'm not sure what the user was doing before the crash, but I suspect the PC was going/returning from sleep/hibernate.

Application: zVirtualDesktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at System.RuntimeTypeHandle.CreateInstance(System.RuntimeType, Boolean, Boolean, Boolean ByRef, System.RuntimeMethodHandleInternal ByRef, Boolean ByRef)
   at System.RuntimeType.CreateInstanceSlow(Boolean, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Activator.CreateInstance(System.Type, Boolean)
   at System.Activator.CreateInstance(System.Type)
   at WindowsDesktop.Interop.VirtualDesktopManagerInternal.GetInstanceCore[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]()
   at WindowsDesktop.Interop.VirtualDesktopManagerInternal.GetInstance()
   at WindowsDesktop.Interop.ComObjects.Initialize()
   at WindowsDesktop.Interop.ComObjects+<>c.<Initialize>b__23_0()
   at WindowsDesktop.Interop.ComObjects+ExplorerRestartListenerWindow.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by mzomparelli** [comment]
Nothing new on this so I'm closing it.
